workspace(name = "leetcode")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository", "new_git_repository")

# Group the sources of the library so that CMake rule have access to it
all_content = """filegroup(name = "all", srcs = glob(["**"]), visibility = ["//visibility:public"])"""

http_archive(
   name = "rules_foreign_cc",
   strip_prefix = "rules_foreign_cc-master",
   url = "https://github.com/bazelbuild/rules_foreign_cc/archive/master.zip",
)
load("@rules_foreign_cc//:workspace_definitions.bzl", "rules_foreign_cc_dependencies")
rules_foreign_cc_dependencies()

#http_archive(
#    name = "rules_cc",
#    strip_prefix = "rules_cc-master",
#    urls = ["https://github.com/bazelbuild/rules_cc/archive/master.zip"],
#)

load("//third_party:third_party_repositories.bzl", "include_third_party_repositories")
include_third_party_repositories()
