cc_library(
    name = "common",
    deps = [
        "//src/include:data_structure",
        "//src/include/algorithms",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "input",
    srcs = ["input.cc"],
    deps = [":common"],
)

cc_test(
    name = "heap_test",
    srcs = ["heap_test.cc"],
    deps = [":common"],
)

cc_test(
    name = "combination_test",
    srcs = ["combination_test.cc"],
    deps = [":common"],
)

cc_test(
    name = "permutation_test",
    srcs = ["permutation_test.cc"],
    deps = [":common"],
)

cc_test(
    name = "trie_test",
    srcs = ["trie_test.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00002",
    srcs = ["P-00002.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00003",
    srcs = ["P-00003.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00004",
    srcs = ["P-00004.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00015",
    srcs = ["P-00015.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00021",
    srcs = ["P-00021.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00023",
    srcs = ["P-00023.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00033",
    srcs = ["P-00033.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00046",
    srcs = ["P-00046.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00048",
    srcs = ["P-00048.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00054",
    srcs = ["P-00054.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00061",
    srcs = ["P-00061.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00064",
    srcs = ["P-00064.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00069",
    srcs = ["P-00069.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00076",
    srcs = ["P-00076.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00082",
    srcs = ["P-00082.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00083",
    srcs = ["P-00083.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00094",
    srcs = ["P-00094.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00102",
    srcs = ["P-00102.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00103",
    srcs = ["P-00103.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00105",
    srcs = ["P-00105.cc"],
    deps = [":common"], 
)

cc_test(
    name = "P-00110",
    srcs = ["P-00110.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00121",
    srcs = ["P-00121.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00124",
    srcs = ["P-00124.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00128",
    srcs = ["P-00128.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00139",
    srcs = ["P-00139.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00143",
    srcs = ["P-00143.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00144",
    srcs = ["P-00144.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00145",
    srcs = ["P-00145.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00160",
    srcs = ["P-00160.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00206",
    srcs = ["P-00206.cc"],
    deps = [":common"],
)
