cc_library(
    name = "common",
    deps = [
        "//src/include:data_structure",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "input",
    srcs = ["input.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00002",
    srcs = ["P-00002.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00003",
    srcs = ["P-00003.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00004",
    srcs = ["P-00004.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00015",
    srcs = ["P-00015.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00021",
    srcs = ["P-00021.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00023",
    srcs = ["P-00023.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00033",
    srcs = ["P-00033.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00046",
    srcs = ["P-00046.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00048",
    srcs = ["P-00048.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00054",
    srcs = ["P-00054.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00061",
    srcs = ["P-00061.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00064",
    srcs = ["P-00064.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00069",
    srcs = ["P-00069.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00206",
    srcs = ["P-00206.cc"],
    deps = [":common"],
)
