cc_library(
    name = "common",
    deps = [
        "//src/include:data_structure",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "P-00002",
    srcs = ["P-00002.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00003",
    srcs = ["P-00003.cc"],
    deps = [":common"],
)

cc_test(
    name = "P-00004",
    srcs = ["P-00004.cc"],
    deps = [":common"],
)
