cc_binary(
   name = "OJ-00001",
   srcs = ["OJ-00001.cc"],
   deps = [],
)

cc_binary(
   name = "OJ-00002",
   srcs = ["OJ-00002.cc"],
   deps = [],
)

cc_binary(
   name = "OJ-00003",
   srcs = ["OJ-00003.cc"],
   deps = [],
)

cc_binary(
   name = "OJ-00004",
   srcs = ["OJ-00004.cc"],
   deps = [
   ],
)

