cc_binary(
   name = "OJ-00001",
   srcs = ["OJ-00001.cc"],
   deps = [],
)

cc_binary(
   name = "OJ-00002",
   srcs = ["OJ-00002.cc"],
   deps = [],
)

cc_binary(
   name = "OJ-00003",
   srcs = ["OJ-00003.cc"],
   deps = [],
)

cc_binary(
   name = "OJ-00004",
   srcs = ["OJ-00004.cc"],
   deps = [],
)

cc_binary(
   name = "OJ-00005",
   srcs = ["OJ-00005.cc"],
   deps = [],
)

cc_binary(
   name = "OJ-00006",
   srcs = ["OJ-00006.cc"],
   deps = [],
)

cc_binary(
   name = "OJ-00007",
   srcs = ["OJ-00007.cc"],
   deps = [],
)

cc_binary(
   name = "OJ-00008",
   srcs = ["OJ-00008.cc"],
   deps = [],
)

